// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV4bnbqark8NOVPdxPCwm69O3EPU0fAqI',
    appId: '1:570991179221:web:8232e39e4f49a3bbaa395c',
    messagingSenderId: '570991179221',
    projectId: 'travelai-88a07',
    authDomain: 'travelai-88a07.firebaseapp.com',
    storageBucket: 'travelai-88a07.appspot.com',
    measurementId: 'G-X9JCRXGX9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFA57XISN0ufZwIb8WImUnvefeylkkNH8',
    appId: '1:570991179221:android:ece979376b28b427aa395c',
    messagingSenderId: '570991179221',
    projectId: 'travelai-88a07',
    storageBucket: 'travelai-88a07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAmJDVwxia6b5PDbTSBRSbcW9ul0cJhLg',
    appId: '1:570991179221:ios:ea80522d84d25f8caa395c',
    messagingSenderId: '570991179221',
    projectId: 'travelai-88a07',
    storageBucket: 'travelai-88a07.appspot.com',
    androidClientId: '570991179221-nb68np7lfp1rpr8k00amgb99hm3i6vmp.apps.googleusercontent.com',
    iosClientId: '570991179221-ohqp7sd35ep87smeho4vqibonej3lm54.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelAiFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAmJDVwxia6b5PDbTSBRSbcW9ul0cJhLg',
    appId: '1:570991179221:ios:ea80522d84d25f8caa395c',
    messagingSenderId: '570991179221',
    projectId: 'travelai-88a07',
    storageBucket: 'travelai-88a07.appspot.com',
    iosClientId: '570991179221-ohqp7sd35ep87smeho4vqibonej3lm54.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelAiFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV4bnbqark8NOVPdxPCwm69O3EPU0fAqI',
    appId: '1:570991179221:web:96d1fab1819ca8f8aa395c',
    messagingSenderId: '570991179221',
    projectId: 'travelai-88a07',
    authDomain: 'travelai-88a07.firebaseapp.com',
    storageBucket: 'travelai-88a07.appspot.com',
    measurementId: 'G-3T4SM2E1EG',
  );

}