steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/travelai-88a07/travelbuddyrepo/travelbuddyback:latest'  # Replace 'your-image-name' with your desired image name
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/travelai-88a07/travelbuddyrepo/travelbuddyback:latest'